src/Entity/Proveedores.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProveedoresRepository")
 */
class Proveedores
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     * @Assert\Type("string")
     * @Assert\NotBlank
     */
    private $Nombre;

    /**
     * @ORM\Column(type="string", length=50, unique=true)
     * @Assert\NotBlank
     */
    private $Correo;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     * @Assert\NotBlank
     */
    private $Telefono;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     * @Assert\Type("string")
     * @Assert\NotBlank
     */
    private $Producto;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     * @Assert\Type("string")
     * @Assert\NotBlank
     */
    private $Responsable;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     * @Assert\NotBlank
     */
    private $Direccion;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->Nombre;
    }

    public function setNombre(string $Nombre): self
    {
        $this->Nombre = $Nombre;

        return $this;
    }

    public function getCorreo(): ?string
    {
        return $this->Correo;
    }

    public function setCorreo(?string $Correo): self
    {
        $this->Correo = $Correo;

        return $this;
    }

    public function getTelefono(): ?string
    {
        return $this->Telefono;
    }

    public function getProducto(): ?string
    {
        return $this->Producto;
    }

    public function setTelefono(?string $Telefono): self
    {
        $this->Telefono = $Telefono;

        return $this;
    }

    public function setProducto(?string $Producto): self
    {
        $this->Producto = $Producto;

        return $this;
    }

    public function getResponsable(): ?string
    {
        return $this->Responsable;
    }

    public function setResponsable(?string $Responsable): self
    {
        $this->Responsable = $Responsable;

        return $this;
    }

    public function getDireccion(): ?string
    {
        return $this->Direccion;
    }

    public function setDireccion(?string $Direccion): self
    {
        $this->Direccion = $Direccion;

        return $this;
    }
}

src/Form/ProveedoresType.php
<?php

namespace App\Form;

use App\Entity\Proveedores;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;

class ProveedoresType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Nombre')
            ->add('Correo', EmailType::class)
            ->add('Producto')
            ->add('Telefono', NumberType::class)
            ->add('Responsable')
            ->add('Direccion')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Proveedores::class,
        ]);
    }
}

src/Controller/ProveedoresController.php
<?php

namespace App\Controller;

use App\Entity\Proveedores;
use App\Entity\Clientes;
use App\Form\ProveedoresType;
use App\Form\ClientesType;
use App\Repository\ProveedoresRepository;
use App\Repository\ClientesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Esta clase es el controlador de los proveedores.
 * Tiene todos los metodos necesarios para poder trabajar con los proveedores guardados en la bbdd.
 * @Route("/proveedores")
 * @author Ivan
 */
class ProveedoresController extends AbstractController
{
    /**
     * Muestra todos los proveedores y clientes guardados en la bbdd
     * @Route("/", name="proveedores_index", methods={"GET"})
     * @param proveedoresRepository Inyeccion de dependencias de la clase ProveedoresRepository 
     * @param a Inyeccion de dependencias de la clase ClientesRepository
     * @return proveedores Renderiza todos los proveedores de la bbdd
     * @return clientes Renderiza todos los clientes de la bbdd
     */
    public function index(ProveedoresRepository $proveedoresRepository, ClientesRepository $a): Response
    {
        return $this->render('proveedores/index.html.twig', [
            'proveedores' => $proveedoresRepository->findAll(),
            'clientes' => $a->findAll()
        ]);
    }

    /**
     * Crea un nuevo proveedor en la bbdd
     * @Route("/new", name="proveedores_new", methods={"GET","POST"})
     * @param request Inyeccion de dependencias de la clase Request de symfony
     * @return proveedore Renderiza los datos del proveedor a introducir en la bbdd
     * @return form Renderiza el formulario para la creacion del proveedor
     */
    public function new(Request $request): Response
    {
        $proveedore = new Proveedores();
        $form = $this->createForm(ProveedoresType::class, $proveedore);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($proveedore);
            $entityManager->flush();

            return $this->redirectToRoute('proveedores_index');
        }

        return $this->render('proveedores/new.html.twig', [
            'proveedore' => $proveedore,
            'form' => $form->createView(),
        ]);
    }

    /**
     * Muestra la información del proveedor seleccionado
     * @Route("/{id}", name="proveedores_show", methods={"GET"})
     * @param proveedore Inyeccion de dependencias de la clase Entity/Proveedores
     */
    public function show(Proveedores $proveedore): Response
    {
        return $this->render('proveedores/show.html.twig', [
            'proveedore' => $proveedore,
        ]);
    }

    /**
     * Edita la informacion de un proveedor seleccionado
     * @Route("/{id}/edit", name="proveedores_edit", methods={"GET","POST"})
     * @param request Inyeccion de dependencias de la clase Request de symfony
     * @param proveedore Inyeccion de dependencias de la clase Entity/Proveedores
     * @return id Redirige al index el identificador del proveedor seleccionado
     * @return proveedore Renderiza la informacion editada del proveedor seleccionado 
     * @return form Renderiza el formulario para editar la informacion del proveedor
     */
    public function edit(Request $request, Proveedores $proveedore): Response
    {
        $form = $this->createForm(ProveedoresType::class, $proveedore);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('proveedores_index', [
                'id' => $proveedore->getId(),
            ]);
        }

        return $this->render('proveedores/edit.html.twig', [
            'proveedore' => $proveedore,
            'form' => $form->createView(),
        ]);
    }

    /**
     * Elimina un proveedor seleccionado
     * @Route("/{id}", name="proveedores_delete", methods={"DELETE"})
     * @param request Inyeccion de dependencias de la clase Request de symfony
     * @param proveedore Inyeccion de dependencias de la clase Entity/Proveedores
     */
    public function delete(Request $request, Proveedores $proveedore): Response
    {
        if ($this->isCsrfTokenValid('delete'.$proveedore->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($proveedore);
            $entityManager->flush();
        }

        return $this->redirectToRoute('proveedores_index');
    }

    
}

templates/proveedores/_delete_form.html.twig
<form method="post" action="{{ path('proveedores_delete', {'id': proveedore.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ proveedore.id) }}">
    <button class="btn">Eliminar</button>
</form>

templates/proveedores/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Guardar') }}</button>
{{ form_end(form) }}

templates/proveedores/edit.html.twig
{% extends 'nav.html.twig' %}

{% block title %}Edit Proveedores{% endblock %}

{% block content %}
<body>
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
    <h1>Editar la información del proveedor</h1>

    {{ include('proveedores/_form.html.twig', {'button_label': 'Actualizar'}) }}

    <br>

    <button class="btn"><a href="{{ path('proveedores_index') }}">Volver a la lista de clientes y proveedores</a></button>


    <br>
    <br>
    
    {{ include('proveedores/_delete_form.html.twig') }}

</main>
</body>
{% endblock %}

templates/proveedores/index.html.twig
{% extends 'nav.html.twig' %}

{% block title %}Proveedores index{% endblock %}

{% block content %}
    

<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">

<br>
<br>


    <div class="row">
                  

         <div class="table-responsive col-md-5">
            <h3>Proveedores</h3>
             <a href="{{ path('proveedores_new') }}"></a>
             
            <table class="table table-bordered table-striped table-sm">
                    <thead>
                        <tr>
                            
                            <th>Nombre</th>
                            <th>Producto</th>
                            <th></th>
                
                        </tr>
                    </thead>
        <tbody>

        {% for proveedore in proveedores %}
        
            <tr>
                <td>{{ proveedore.Nombre }}</td>
                <td>{{ proveedore.producto }}</td>
                <td>
                    
                   
                    
                    <a style="float:left; margin-left:2%;" href="{{ path('proveedores_show', {'id': proveedore.id}) }}"><img src="../../../img/lupa.png"  width="30px" height="30px"></a>
            
                    
                    {% if is_granted('ROLE_ADMIN') %}

                    <form method="post" style="float:left; margin-left:2%;" action="{{ path('proveedores_delete', {'id': proveedore.id}) }}" onsubmit="return confirm('Estás seguro que desea eliminar el proveedor?');">
                            <input type="hidden" name="_method" value="DELETE">
                            <input type="image" src="../../../img/basurita.png" width="30px" height="30px"/>
                            <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ proveedore.id) }}">
                    </form>

                    <a style="float:left; margin-left:2%;" href="{{ path('proveedores_edit', {'id': proveedore.id}) }}"><img src="../../../img/edit.png"  width="30px" height="30px"></a>

                      

                
                {% endif %}  
                </td>
            </tr>

        {% else %}
            <tr>
                <td colspan="7">No hay ningún proveedor activo</td>
            </tr>
        {% endfor %}

        </tbody>

        </table>

         {% if is_granted('ROLE_ADMIN') %}
            <a style="float:right;" href="{{ path('proveedores_new') }}"><img  width="30px" height="30px" src="../../../../img/mas.png"></a>
         {% endif %} 
    </div>

        
    <div class="table-responsive col-md-5">

        <h3>Clientes</h3>
         <table class="table table-bordered table-striped table-sm">

                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Servicio</th>
                        <th></th>
                         
                         
                    </tr>
                </thead>
         <tbody>

                        
                {% for us in clientes %}

                    <tr>
                          <td> {{us.Nombre}} </td>
                          <td> {{us.Correo}} </td>
                            <td>
                    
                   
                    
                            <a style="float:left; margin-left:2%;" href="{{ path('clientes_show', {'id': us.id}) }}"><img src="../../../img/lupa.png"  width="30px" height="30px"></a>
                    
                            
                            {% if is_granted('ROLE_ADMIN') %}

                            <form method="post" style="float:left; margin-left:2%;" action="{{ path('clientes_delete', {'id': us.id}) }}" onsubmit="return confirm('Estás seguro que desea eliminar el proveedor?');">
                                    <input type="hidden" name="_method" value="DELETE">
                                    <input type="image" src="../../../img/basurita.png" width="30px" height="30px"/>
                                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ us.id) }}">
                            </form>

                            <a style="float:left; margin-left:2%;" href="{{ path('clientes_edit', {'id': us.id}) }}"><img src="../../../img/edit.png"  width="30px" height="30px"></a>

                      

                
                {% endif %}  
                </td>
                         {% else %}

                         <tr>
                             <td colspan="7">No hay ningún cliente activo</td>
                        </tr>
                {% endfor %}
                          
                          
                    </tr>               
                    </tbody>
                    </table>

                     <a style="float:right;" href="{{ path('clientes_new') }}"><img  width="30px" height="30px" src="../../../../img/mas.png"></a>
            </div>
        </div>
    </table>

</main>
{% endblock %}

templates/proveedores/new.html.twig
{% extends 'nav.html.twig' %}
{% block title %}New Proveedores{% endblock %}

{% block content %}
<body>
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
    <h1>Registrar a un nuevo proveedor de la empresa</h1>

    {{ include('proveedores/_form.html.twig') }}

    <a href="{{ path('proveedores_index') }}">Volver a la lista de clientes y proveedores</a>

</main>
</body>
{% endblock %}

templates/proveedores/show.html.twig
{% extends 'nav.html.twig' %}

{% block title %}Proveedores{% endblock %}

{% block content %}

    <body>
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">

    <h1>Información del proveedor <b>{{proveedore.Nombre}}</b></h1>

    

    <table class="table">
        <tbody>
            <tr>
                <th>Correo</th>
                <td>{{ proveedore.Correo }}</td>
            </tr>
            <tr>
                <th>Telefono</th>
                <td>{{ proveedore.Telefono }}</td>
            </tr>
            <tr>
                <th>Responsable</th>
                <td>{{ proveedore.Responsable }}</td>
            </tr>
            <tr>
                <th>Direccion</th>
                <td>{{ proveedore.Direccion }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('proveedores_index') }}">Volver a la lista de proveedores</a>
     {% if is_granted('ROLE_ADMIN') %}
     
    <a href="{{ path('proveedores_edit', {'id': proveedore.id}) }}">Editar proveedor</a>


    {{ include('proveedores/_delete_form.html.twig') }}

    {% endif %} 


    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
    </body>
{% endblock %}